# Generated by Django 5.2.1 on 2025-05-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('avg_rating', 'Average Rating'), ('cultural_score', 'Cultural Appropriateness Score'), ('response_time', 'Average Response Time'), ('feedback_count', 'Feedback Count'), ('common_issue', 'Common Issue')], max_length=20)),
                ('value', models.FloatField()),
                ('text_value', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('medical_accuracy', models.PositiveSmallIntegerField()),
                ('cultural_relevance', models.PositiveSmallIntegerField()),
                ('suggested_correction', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to='api.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(blank=True, default=dict)),
                ('symptom_durations', models.JSONField(blank=True, default=dict)),
                ('treatments_tried', models.JSONField(blank=True, default=list)),
                ('medical_history', models.JSONField(blank=True, default=list)),
                ('cultural_preferences', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_context', to='api.conversationsession')),
            ],
        ),
    ]
